//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhieuThuePhongDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceQuanLyKhachSan")]
    [System.SerializableAttribute()]
    public partial class PhieuThuePhongDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaphieudatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaphieuthueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Maphieudat {
            get {
                return this.MaphieudatField;
            }
            set {
                if ((object.ReferenceEquals(this.MaphieudatField, value) != true)) {
                    this.MaphieudatField = value;
                    this.RaisePropertyChanged("Maphieudat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Maphieuthue {
            get {
                return this.MaphieuthueField;
            }
            set {
                if ((object.ReferenceEquals(this.MaphieuthueField, value) != true)) {
                    this.MaphieuthueField = value;
                    this.RaisePropertyChanged("Maphieuthue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencePhieuThuePhong.IServicePhieuThuePhong")]
    public interface IServicePhieuThuePhong {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuThuePhong/CountListPTP", ReplyAction="http://tempuri.org/IServicePhieuThuePhong/CountListPTPResponse")]
        int CountListPTP();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuThuePhong/CountListPTP", ReplyAction="http://tempuri.org/IServicePhieuThuePhong/CountListPTPResponse")]
        System.Threading.Tasks.Task<int> CountListPTPAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuThuePhong/getListPhieuThuePhongAll", ReplyAction="http://tempuri.org/IServicePhieuThuePhong/getListPhieuThuePhongAllResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO[] getListPhieuThuePhongAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuThuePhong/getListPhieuThuePhongAll", ReplyAction="http://tempuri.org/IServicePhieuThuePhong/getListPhieuThuePhongAllResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO[]> getListPhieuThuePhongAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuThuePhong/getListPhieuThuePhongLMAll", ReplyAction="http://tempuri.org/IServicePhieuThuePhong/getListPhieuThuePhongLMAllResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO[] getListPhieuThuePhongLMAll(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuThuePhong/getListPhieuThuePhongLMAll", ReplyAction="http://tempuri.org/IServicePhieuThuePhong/getListPhieuThuePhongLMAllResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO[]> getListPhieuThuePhongLMAllAsync(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuThuePhong/getPhieuThuePhongByID", ReplyAction="http://tempuri.org/IServicePhieuThuePhong/getPhieuThuePhongByIDResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO getPhieuThuePhongByID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuThuePhong/getPhieuThuePhongByID", ReplyAction="http://tempuri.org/IServicePhieuThuePhong/getPhieuThuePhongByIDResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO> getPhieuThuePhongByIDAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuThuePhong/getListPhieuThuePhongByMaPhieuDat", ReplyAction="http://tempuri.org/IServicePhieuThuePhong/getListPhieuThuePhongByMaPhieuDatRespon" +
            "se")]
        WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO[] getListPhieuThuePhongByMaPhieuDat(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuThuePhong/getListPhieuThuePhongByMaPhieuDat", ReplyAction="http://tempuri.org/IServicePhieuThuePhong/getListPhieuThuePhongByMaPhieuDatRespon" +
            "se")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO[]> getListPhieuThuePhongByMaPhieuDatAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuThuePhong/getLikePhieuThuePhongByID", ReplyAction="http://tempuri.org/IServicePhieuThuePhong/getLikePhieuThuePhongByIDResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO[] getLikePhieuThuePhongByID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuThuePhong/getLikePhieuThuePhongByID", ReplyAction="http://tempuri.org/IServicePhieuThuePhong/getLikePhieuThuePhongByIDResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO[]> getLikePhieuThuePhongByIDAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuThuePhong/getListLikePhieuThuePhongByMaPhieuDat", ReplyAction="http://tempuri.org/IServicePhieuThuePhong/getListLikePhieuThuePhongByMaPhieuDatRe" +
            "sponse")]
        WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO[] getListLikePhieuThuePhongByMaPhieuDat(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuThuePhong/getListLikePhieuThuePhongByMaPhieuDat", ReplyAction="http://tempuri.org/IServicePhieuThuePhong/getListLikePhieuThuePhongByMaPhieuDatRe" +
            "sponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO[]> getListLikePhieuThuePhongByMaPhieuDatAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuThuePhong/insertPhieuThuePhong", ReplyAction="http://tempuri.org/IServicePhieuThuePhong/insertPhieuThuePhongResponse")]
        int insertPhieuThuePhong(WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO ptpDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuThuePhong/insertPhieuThuePhong", ReplyAction="http://tempuri.org/IServicePhieuThuePhong/insertPhieuThuePhongResponse")]
        System.Threading.Tasks.Task<int> insertPhieuThuePhongAsync(WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO ptpDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuThuePhong/deletePhieuThuePhong", ReplyAction="http://tempuri.org/IServicePhieuThuePhong/deletePhieuThuePhongResponse")]
        int deletePhieuThuePhong(string IDPhieuThuePhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuThuePhong/deletePhieuThuePhong", ReplyAction="http://tempuri.org/IServicePhieuThuePhong/deletePhieuThuePhongResponse")]
        System.Threading.Tasks.Task<int> deletePhieuThuePhongAsync(string IDPhieuThuePhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuThuePhong/updatePhieuThuePhong", ReplyAction="http://tempuri.org/IServicePhieuThuePhong/updatePhieuThuePhongResponse")]
        int updatePhieuThuePhong(WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO ptpDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuThuePhong/updatePhieuThuePhong", ReplyAction="http://tempuri.org/IServicePhieuThuePhong/updatePhieuThuePhongResponse")]
        System.Threading.Tasks.Task<int> updatePhieuThuePhongAsync(WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO ptpDTO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicePhieuThuePhongChannel : WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.IServicePhieuThuePhong, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePhieuThuePhongClient : System.ServiceModel.ClientBase<WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.IServicePhieuThuePhong>, WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.IServicePhieuThuePhong {
        
        public ServicePhieuThuePhongClient() {
        }
        
        public ServicePhieuThuePhongClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePhieuThuePhongClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePhieuThuePhongClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePhieuThuePhongClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CountListPTP() {
            return base.Channel.CountListPTP();
        }
        
        public System.Threading.Tasks.Task<int> CountListPTPAsync() {
            return base.Channel.CountListPTPAsync();
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO[] getListPhieuThuePhongAll() {
            return base.Channel.getListPhieuThuePhongAll();
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO[]> getListPhieuThuePhongAllAsync() {
            return base.Channel.getListPhieuThuePhongAllAsync();
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO[] getListPhieuThuePhongLMAll(int a) {
            return base.Channel.getListPhieuThuePhongLMAll(a);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO[]> getListPhieuThuePhongLMAllAsync(int a) {
            return base.Channel.getListPhieuThuePhongLMAllAsync(a);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO getPhieuThuePhongByID(string id) {
            return base.Channel.getPhieuThuePhongByID(id);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO> getPhieuThuePhongByIDAsync(string id) {
            return base.Channel.getPhieuThuePhongByIDAsync(id);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO[] getListPhieuThuePhongByMaPhieuDat(string name) {
            return base.Channel.getListPhieuThuePhongByMaPhieuDat(name);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO[]> getListPhieuThuePhongByMaPhieuDatAsync(string name) {
            return base.Channel.getListPhieuThuePhongByMaPhieuDatAsync(name);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO[] getLikePhieuThuePhongByID(string id) {
            return base.Channel.getLikePhieuThuePhongByID(id);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO[]> getLikePhieuThuePhongByIDAsync(string id) {
            return base.Channel.getLikePhieuThuePhongByIDAsync(id);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO[] getListLikePhieuThuePhongByMaPhieuDat(string name) {
            return base.Channel.getListLikePhieuThuePhongByMaPhieuDat(name);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO[]> getListLikePhieuThuePhongByMaPhieuDatAsync(string name) {
            return base.Channel.getListLikePhieuThuePhongByMaPhieuDatAsync(name);
        }
        
        public int insertPhieuThuePhong(WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO ptpDTO) {
            return base.Channel.insertPhieuThuePhong(ptpDTO);
        }
        
        public System.Threading.Tasks.Task<int> insertPhieuThuePhongAsync(WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO ptpDTO) {
            return base.Channel.insertPhieuThuePhongAsync(ptpDTO);
        }
        
        public int deletePhieuThuePhong(string IDPhieuThuePhong) {
            return base.Channel.deletePhieuThuePhong(IDPhieuThuePhong);
        }
        
        public System.Threading.Tasks.Task<int> deletePhieuThuePhongAsync(string IDPhieuThuePhong) {
            return base.Channel.deletePhieuThuePhongAsync(IDPhieuThuePhong);
        }
        
        public int updatePhieuThuePhong(WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO ptpDTO) {
            return base.Channel.updatePhieuThuePhong(ptpDTO);
        }
        
        public System.Threading.Tasks.Task<int> updatePhieuThuePhongAsync(WCF_QuanLyKhachSanForm.ServiceReferencePhieuThuePhong.PhieuThuePhongDTO ptpDTO) {
            return base.Channel.updatePhieuThuePhongAsync(ptpDTO);
        }
    }
}
