//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_QuanLyKhachSanForm.ServiceReferenceKiemTraPhong {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KiemTraPhongDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceQuanLyKhachSan")]
    [System.SerializableAttribute()]
    public partial class KiemTraPhongDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaphieudatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaphongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgaydenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgaydiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TinhtrangField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Maphieudat {
            get {
                return this.MaphieudatField;
            }
            set {
                if ((object.ReferenceEquals(this.MaphieudatField, value) != true)) {
                    this.MaphieudatField = value;
                    this.RaisePropertyChanged("Maphieudat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Maphong {
            get {
                return this.MaphongField;
            }
            set {
                if ((object.ReferenceEquals(this.MaphongField, value) != true)) {
                    this.MaphongField = value;
                    this.RaisePropertyChanged("Maphong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Ngayden {
            get {
                return this.NgaydenField;
            }
            set {
                if ((this.NgaydenField.Equals(value) != true)) {
                    this.NgaydenField = value;
                    this.RaisePropertyChanged("Ngayden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Ngaydi {
            get {
                return this.NgaydiField;
            }
            set {
                if ((this.NgaydiField.Equals(value) != true)) {
                    this.NgaydiField = value;
                    this.RaisePropertyChanged("Ngaydi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tinhtrang {
            get {
                return this.TinhtrangField;
            }
            set {
                if ((object.ReferenceEquals(this.TinhtrangField, value) != true)) {
                    this.TinhtrangField = value;
                    this.RaisePropertyChanged("Tinhtrang");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceKiemTraPhong.IServiceKiemTraPhong")]
    public interface IServiceKiemTraPhong {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceKiemTraPhong/KiemTraPhong", ReplyAction="http://tempuri.org/IServiceKiemTraPhong/KiemTraPhongResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceKiemTraPhong.KiemTraPhongDTO[] KiemTraPhong(System.DateTime ngayden, System.DateTime ngaydi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceKiemTraPhong/KiemTraPhong", ReplyAction="http://tempuri.org/IServiceKiemTraPhong/KiemTraPhongResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceKiemTraPhong.KiemTraPhongDTO[]> KiemTraPhongAsync(System.DateTime ngayden, System.DateTime ngaydi);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceKiemTraPhongChannel : WCF_QuanLyKhachSanForm.ServiceReferenceKiemTraPhong.IServiceKiemTraPhong, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceKiemTraPhongClient : System.ServiceModel.ClientBase<WCF_QuanLyKhachSanForm.ServiceReferenceKiemTraPhong.IServiceKiemTraPhong>, WCF_QuanLyKhachSanForm.ServiceReferenceKiemTraPhong.IServiceKiemTraPhong {
        
        public ServiceKiemTraPhongClient() {
        }
        
        public ServiceKiemTraPhongClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceKiemTraPhongClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceKiemTraPhongClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceKiemTraPhongClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceKiemTraPhong.KiemTraPhongDTO[] KiemTraPhong(System.DateTime ngayden, System.DateTime ngaydi) {
            return base.Channel.KiemTraPhong(ngayden, ngaydi);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceKiemTraPhong.KiemTraPhongDTO[]> KiemTraPhongAsync(System.DateTime ngayden, System.DateTime ngaydi) {
            return base.Channel.KiemTraPhongAsync(ngayden, ngaydi);
        }
    }
}
