//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChiTietDatPhongDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceQuanLyKhachSan")]
    [System.SerializableAttribute()]
    public partial class ChiTietDatPhongDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaphieudatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaphongField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Maphieudat {
            get {
                return this.MaphieudatField;
            }
            set {
                if ((object.ReferenceEquals(this.MaphieudatField, value) != true)) {
                    this.MaphieudatField = value;
                    this.RaisePropertyChanged("Maphieudat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Maphong {
            get {
                return this.MaphongField;
            }
            set {
                if ((object.ReferenceEquals(this.MaphongField, value) != true)) {
                    this.MaphongField = value;
                    this.RaisePropertyChanged("Maphong");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceChiTietDatPhong.IServiceChiTietDatPhong")]
    public interface IServiceChiTietDatPhong {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietDatPhong/CountListctdp", ReplyAction="http://tempuri.org/IServiceChiTietDatPhong/CountListctdpResponse")]
        int CountListctdp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietDatPhong/CountListctdp", ReplyAction="http://tempuri.org/IServiceChiTietDatPhong/CountListctdpResponse")]
        System.Threading.Tasks.Task<int> CountListctdpAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietDatPhong/getListChiTietDatPhongAll", ReplyAction="http://tempuri.org/IServiceChiTietDatPhong/getListChiTietDatPhongAllResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO[] getListChiTietDatPhongAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietDatPhong/getListChiTietDatPhongAll", ReplyAction="http://tempuri.org/IServiceChiTietDatPhong/getListChiTietDatPhongAllResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO[]> getListChiTietDatPhongAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietDatPhong/getListChiTietDatPhongLMAll", ReplyAction="http://tempuri.org/IServiceChiTietDatPhong/getListChiTietDatPhongLMAllResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO[] getListChiTietDatPhongLMAll(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietDatPhong/getListChiTietDatPhongLMAll", ReplyAction="http://tempuri.org/IServiceChiTietDatPhong/getListChiTietDatPhongLMAllResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO[]> getListChiTietDatPhongLMAllAsync(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietDatPhong/getChiTietDatPhongByID", ReplyAction="http://tempuri.org/IServiceChiTietDatPhong/getChiTietDatPhongByIDResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO[] getChiTietDatPhongByID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietDatPhong/getChiTietDatPhongByID", ReplyAction="http://tempuri.org/IServiceChiTietDatPhong/getChiTietDatPhongByIDResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO[]> getChiTietDatPhongByIDAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietDatPhong/getListChiTietDatPhongByName", ReplyAction="http://tempuri.org/IServiceChiTietDatPhong/getListChiTietDatPhongByNameResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO[] getListChiTietDatPhongByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietDatPhong/getListChiTietDatPhongByName", ReplyAction="http://tempuri.org/IServiceChiTietDatPhong/getListChiTietDatPhongByNameResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO[]> getListChiTietDatPhongByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietDatPhong/getLikeChiTietDatPhongByID", ReplyAction="http://tempuri.org/IServiceChiTietDatPhong/getLikeChiTietDatPhongByIDResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO[] getLikeChiTietDatPhongByID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietDatPhong/getLikeChiTietDatPhongByID", ReplyAction="http://tempuri.org/IServiceChiTietDatPhong/getLikeChiTietDatPhongByIDResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO[]> getLikeChiTietDatPhongByIDAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietDatPhong/getListLikeChiTietDatPhongByName", ReplyAction="http://tempuri.org/IServiceChiTietDatPhong/getListLikeChiTietDatPhongByNameRespon" +
            "se")]
        WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO[] getListLikeChiTietDatPhongByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietDatPhong/getListLikeChiTietDatPhongByName", ReplyAction="http://tempuri.org/IServiceChiTietDatPhong/getListLikeChiTietDatPhongByNameRespon" +
            "se")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO[]> getListLikeChiTietDatPhongByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietDatPhong/insertChiTietDatPhong", ReplyAction="http://tempuri.org/IServiceChiTietDatPhong/insertChiTietDatPhongResponse")]
        int insertChiTietDatPhong(WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO ctdpDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietDatPhong/insertChiTietDatPhong", ReplyAction="http://tempuri.org/IServiceChiTietDatPhong/insertChiTietDatPhongResponse")]
        System.Threading.Tasks.Task<int> insertChiTietDatPhongAsync(WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO ctdpDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietDatPhong/deleteChiTietDatPhong", ReplyAction="http://tempuri.org/IServiceChiTietDatPhong/deleteChiTietDatPhongResponse")]
        int deleteChiTietDatPhong(string IDChiTietDatPhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietDatPhong/deleteChiTietDatPhong", ReplyAction="http://tempuri.org/IServiceChiTietDatPhong/deleteChiTietDatPhongResponse")]
        System.Threading.Tasks.Task<int> deleteChiTietDatPhongAsync(string IDChiTietDatPhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietDatPhong/updateChiTietDatPhong", ReplyAction="http://tempuri.org/IServiceChiTietDatPhong/updateChiTietDatPhongResponse")]
        int updateChiTietDatPhong(WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO ctdpDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietDatPhong/updateChiTietDatPhong", ReplyAction="http://tempuri.org/IServiceChiTietDatPhong/updateChiTietDatPhongResponse")]
        System.Threading.Tasks.Task<int> updateChiTietDatPhongAsync(WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO ctdpDTO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChiTietDatPhongChannel : WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.IServiceChiTietDatPhong, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceChiTietDatPhongClient : System.ServiceModel.ClientBase<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.IServiceChiTietDatPhong>, WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.IServiceChiTietDatPhong {
        
        public ServiceChiTietDatPhongClient() {
        }
        
        public ServiceChiTietDatPhongClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceChiTietDatPhongClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceChiTietDatPhongClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceChiTietDatPhongClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CountListctdp() {
            return base.Channel.CountListctdp();
        }
        
        public System.Threading.Tasks.Task<int> CountListctdpAsync() {
            return base.Channel.CountListctdpAsync();
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO[] getListChiTietDatPhongAll() {
            return base.Channel.getListChiTietDatPhongAll();
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO[]> getListChiTietDatPhongAllAsync() {
            return base.Channel.getListChiTietDatPhongAllAsync();
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO[] getListChiTietDatPhongLMAll(int a) {
            return base.Channel.getListChiTietDatPhongLMAll(a);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO[]> getListChiTietDatPhongLMAllAsync(int a) {
            return base.Channel.getListChiTietDatPhongLMAllAsync(a);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO[] getChiTietDatPhongByID(string id) {
            return base.Channel.getChiTietDatPhongByID(id);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO[]> getChiTietDatPhongByIDAsync(string id) {
            return base.Channel.getChiTietDatPhongByIDAsync(id);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO[] getListChiTietDatPhongByName(string name) {
            return base.Channel.getListChiTietDatPhongByName(name);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO[]> getListChiTietDatPhongByNameAsync(string name) {
            return base.Channel.getListChiTietDatPhongByNameAsync(name);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO[] getLikeChiTietDatPhongByID(string id) {
            return base.Channel.getLikeChiTietDatPhongByID(id);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO[]> getLikeChiTietDatPhongByIDAsync(string id) {
            return base.Channel.getLikeChiTietDatPhongByIDAsync(id);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO[] getListLikeChiTietDatPhongByName(string name) {
            return base.Channel.getListLikeChiTietDatPhongByName(name);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO[]> getListLikeChiTietDatPhongByNameAsync(string name) {
            return base.Channel.getListLikeChiTietDatPhongByNameAsync(name);
        }
        
        public int insertChiTietDatPhong(WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO ctdpDTO) {
            return base.Channel.insertChiTietDatPhong(ctdpDTO);
        }
        
        public System.Threading.Tasks.Task<int> insertChiTietDatPhongAsync(WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO ctdpDTO) {
            return base.Channel.insertChiTietDatPhongAsync(ctdpDTO);
        }
        
        public int deleteChiTietDatPhong(string IDChiTietDatPhong) {
            return base.Channel.deleteChiTietDatPhong(IDChiTietDatPhong);
        }
        
        public System.Threading.Tasks.Task<int> deleteChiTietDatPhongAsync(string IDChiTietDatPhong) {
            return base.Channel.deleteChiTietDatPhongAsync(IDChiTietDatPhong);
        }
        
        public int updateChiTietDatPhong(WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO ctdpDTO) {
            return base.Channel.updateChiTietDatPhong(ctdpDTO);
        }
        
        public System.Threading.Tasks.Task<int> updateChiTietDatPhongAsync(WCF_QuanLyKhachSanForm.ServiceReferenceChiTietDatPhong.ChiTietDatPhongDTO ctdpDTO) {
            return base.Channel.updateChiTietDatPhongAsync(ctdpDTO);
        }
    }
}
