//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatPhongKhachSanWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ngaydatphong
    {
        public int id { get; set; }
        public Nullable<System.DateTime> ngayden { get; set; }
        public Nullable<System.DateTime> ngaydi { get; set; }
    }
}
