//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatPhongKhachSanWeb.HoaDonServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HoaDonDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceQuanLyKhachSan")]
    [System.SerializableAttribute()]
    public partial class HoaDonDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MahoadonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakhachhangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaphieuthueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgaythanhtoanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TongtienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mahoadon {
            get {
                return this.MahoadonField;
            }
            set {
                if ((object.ReferenceEquals(this.MahoadonField, value) != true)) {
                    this.MahoadonField = value;
                    this.RaisePropertyChanged("Mahoadon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Makhachhang {
            get {
                return this.MakhachhangField;
            }
            set {
                if ((object.ReferenceEquals(this.MakhachhangField, value) != true)) {
                    this.MakhachhangField = value;
                    this.RaisePropertyChanged("Makhachhang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Maphieuthue {
            get {
                return this.MaphieuthueField;
            }
            set {
                if ((object.ReferenceEquals(this.MaphieuthueField, value) != true)) {
                    this.MaphieuthueField = value;
                    this.RaisePropertyChanged("Maphieuthue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Ngaythanhtoan {
            get {
                return this.NgaythanhtoanField;
            }
            set {
                if ((this.NgaythanhtoanField.Equals(value) != true)) {
                    this.NgaythanhtoanField = value;
                    this.RaisePropertyChanged("Ngaythanhtoan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Tongtien {
            get {
                return this.TongtienField;
            }
            set {
                if ((this.TongtienField.Equals(value) != true)) {
                    this.TongtienField = value;
                    this.RaisePropertyChanged("Tongtien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HoaDonServiceReference.IServiceHoaDon")]
    public interface IServiceHoaDon {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHoaDon/CountListHD", ReplyAction="http://tempuri.org/IServiceHoaDon/CountListHDResponse")]
        int CountListHD();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHoaDon/CountListHD", ReplyAction="http://tempuri.org/IServiceHoaDon/CountListHDResponse")]
        System.Threading.Tasks.Task<int> CountListHDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHoaDon/getListHoaDonAll", ReplyAction="http://tempuri.org/IServiceHoaDon/getListHoaDonAllResponse")]
        DatPhongKhachSanWeb.HoaDonServiceReference.HoaDonDTO[] getListHoaDonAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHoaDon/getListHoaDonAll", ReplyAction="http://tempuri.org/IServiceHoaDon/getListHoaDonAllResponse")]
        System.Threading.Tasks.Task<DatPhongKhachSanWeb.HoaDonServiceReference.HoaDonDTO[]> getListHoaDonAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHoaDon/getListHoaDonLMAll", ReplyAction="http://tempuri.org/IServiceHoaDon/getListHoaDonLMAllResponse")]
        DatPhongKhachSanWeb.HoaDonServiceReference.HoaDonDTO[] getListHoaDonLMAll(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHoaDon/getListHoaDonLMAll", ReplyAction="http://tempuri.org/IServiceHoaDon/getListHoaDonLMAllResponse")]
        System.Threading.Tasks.Task<DatPhongKhachSanWeb.HoaDonServiceReference.HoaDonDTO[]> getListHoaDonLMAllAsync(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHoaDon/getHoaDonByID", ReplyAction="http://tempuri.org/IServiceHoaDon/getHoaDonByIDResponse")]
        DatPhongKhachSanWeb.HoaDonServiceReference.HoaDonDTO getHoaDonByID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHoaDon/getHoaDonByID", ReplyAction="http://tempuri.org/IServiceHoaDon/getHoaDonByIDResponse")]
        System.Threading.Tasks.Task<DatPhongKhachSanWeb.HoaDonServiceReference.HoaDonDTO> getHoaDonByIDAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHoaDon/getListHoaDonByDate", ReplyAction="http://tempuri.org/IServiceHoaDon/getListHoaDonByDateResponse")]
        DatPhongKhachSanWeb.HoaDonServiceReference.HoaDonDTO[] getListHoaDonByDate(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHoaDon/getListHoaDonByDate", ReplyAction="http://tempuri.org/IServiceHoaDon/getListHoaDonByDateResponse")]
        System.Threading.Tasks.Task<DatPhongKhachSanWeb.HoaDonServiceReference.HoaDonDTO[]> getListHoaDonByDateAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHoaDon/getLikeHoaDonByID", ReplyAction="http://tempuri.org/IServiceHoaDon/getLikeHoaDonByIDResponse")]
        DatPhongKhachSanWeb.HoaDonServiceReference.HoaDonDTO[] getLikeHoaDonByID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHoaDon/getLikeHoaDonByID", ReplyAction="http://tempuri.org/IServiceHoaDon/getLikeHoaDonByIDResponse")]
        System.Threading.Tasks.Task<DatPhongKhachSanWeb.HoaDonServiceReference.HoaDonDTO[]> getLikeHoaDonByIDAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHoaDon/insertHoaDon", ReplyAction="http://tempuri.org/IServiceHoaDon/insertHoaDonResponse")]
        int insertHoaDon(DatPhongKhachSanWeb.HoaDonServiceReference.HoaDonDTO hdDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHoaDon/insertHoaDon", ReplyAction="http://tempuri.org/IServiceHoaDon/insertHoaDonResponse")]
        System.Threading.Tasks.Task<int> insertHoaDonAsync(DatPhongKhachSanWeb.HoaDonServiceReference.HoaDonDTO hdDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHoaDon/deleteHoaDon", ReplyAction="http://tempuri.org/IServiceHoaDon/deleteHoaDonResponse")]
        int deleteHoaDon(string IDHoaDon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHoaDon/deleteHoaDon", ReplyAction="http://tempuri.org/IServiceHoaDon/deleteHoaDonResponse")]
        System.Threading.Tasks.Task<int> deleteHoaDonAsync(string IDHoaDon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHoaDon/updateHoaDon", ReplyAction="http://tempuri.org/IServiceHoaDon/updateHoaDonResponse")]
        int updateHoaDon(DatPhongKhachSanWeb.HoaDonServiceReference.HoaDonDTO hdDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHoaDon/updateHoaDon", ReplyAction="http://tempuri.org/IServiceHoaDon/updateHoaDonResponse")]
        System.Threading.Tasks.Task<int> updateHoaDonAsync(DatPhongKhachSanWeb.HoaDonServiceReference.HoaDonDTO hdDTO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceHoaDonChannel : DatPhongKhachSanWeb.HoaDonServiceReference.IServiceHoaDon, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceHoaDonClient : System.ServiceModel.ClientBase<DatPhongKhachSanWeb.HoaDonServiceReference.IServiceHoaDon>, DatPhongKhachSanWeb.HoaDonServiceReference.IServiceHoaDon {
        
        public ServiceHoaDonClient() {
        }
        
        public ServiceHoaDonClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceHoaDonClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHoaDonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHoaDonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CountListHD() {
            return base.Channel.CountListHD();
        }
        
        public System.Threading.Tasks.Task<int> CountListHDAsync() {
            return base.Channel.CountListHDAsync();
        }
        
        public DatPhongKhachSanWeb.HoaDonServiceReference.HoaDonDTO[] getListHoaDonAll() {
            return base.Channel.getListHoaDonAll();
        }
        
        public System.Threading.Tasks.Task<DatPhongKhachSanWeb.HoaDonServiceReference.HoaDonDTO[]> getListHoaDonAllAsync() {
            return base.Channel.getListHoaDonAllAsync();
        }
        
        public DatPhongKhachSanWeb.HoaDonServiceReference.HoaDonDTO[] getListHoaDonLMAll(int a) {
            return base.Channel.getListHoaDonLMAll(a);
        }
        
        public System.Threading.Tasks.Task<DatPhongKhachSanWeb.HoaDonServiceReference.HoaDonDTO[]> getListHoaDonLMAllAsync(int a) {
            return base.Channel.getListHoaDonLMAllAsync(a);
        }
        
        public DatPhongKhachSanWeb.HoaDonServiceReference.HoaDonDTO getHoaDonByID(string id) {
            return base.Channel.getHoaDonByID(id);
        }
        
        public System.Threading.Tasks.Task<DatPhongKhachSanWeb.HoaDonServiceReference.HoaDonDTO> getHoaDonByIDAsync(string id) {
            return base.Channel.getHoaDonByIDAsync(id);
        }
        
        public DatPhongKhachSanWeb.HoaDonServiceReference.HoaDonDTO[] getListHoaDonByDate(System.DateTime date) {
            return base.Channel.getListHoaDonByDate(date);
        }
        
        public System.Threading.Tasks.Task<DatPhongKhachSanWeb.HoaDonServiceReference.HoaDonDTO[]> getListHoaDonByDateAsync(System.DateTime date) {
            return base.Channel.getListHoaDonByDateAsync(date);
        }
        
        public DatPhongKhachSanWeb.HoaDonServiceReference.HoaDonDTO[] getLikeHoaDonByID(string id) {
            return base.Channel.getLikeHoaDonByID(id);
        }
        
        public System.Threading.Tasks.Task<DatPhongKhachSanWeb.HoaDonServiceReference.HoaDonDTO[]> getLikeHoaDonByIDAsync(string id) {
            return base.Channel.getLikeHoaDonByIDAsync(id);
        }
        
        public int insertHoaDon(DatPhongKhachSanWeb.HoaDonServiceReference.HoaDonDTO hdDTO) {
            return base.Channel.insertHoaDon(hdDTO);
        }
        
        public System.Threading.Tasks.Task<int> insertHoaDonAsync(DatPhongKhachSanWeb.HoaDonServiceReference.HoaDonDTO hdDTO) {
            return base.Channel.insertHoaDonAsync(hdDTO);
        }
        
        public int deleteHoaDon(string IDHoaDon) {
            return base.Channel.deleteHoaDon(IDHoaDon);
        }
        
        public System.Threading.Tasks.Task<int> deleteHoaDonAsync(string IDHoaDon) {
            return base.Channel.deleteHoaDonAsync(IDHoaDon);
        }
        
        public int updateHoaDon(DatPhongKhachSanWeb.HoaDonServiceReference.HoaDonDTO hdDTO) {
            return base.Channel.updateHoaDon(hdDTO);
        }
        
        public System.Threading.Tasks.Task<int> updateHoaDonAsync(DatPhongKhachSanWeb.HoaDonServiceReference.HoaDonDTO hdDTO) {
            return base.Channel.updateHoaDonAsync(hdDTO);
        }
    }
}
