//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NhanVienDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceQuanLyKhachSan")]
    [System.SerializableAttribute()]
    public partial class NhanVienDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChucvuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiachiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManhanvienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgaysinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PhaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TennhanvienField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Chucvu {
            get {
                return this.ChucvuField;
            }
            set {
                if ((object.ReferenceEquals(this.ChucvuField, value) != true)) {
                    this.ChucvuField = value;
                    this.RaisePropertyChanged("Chucvu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Diachi {
            get {
                return this.DiachiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiachiField, value) != true)) {
                    this.DiachiField = value;
                    this.RaisePropertyChanged("Diachi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Manhanvien {
            get {
                return this.ManhanvienField;
            }
            set {
                if ((object.ReferenceEquals(this.ManhanvienField, value) != true)) {
                    this.ManhanvienField = value;
                    this.RaisePropertyChanged("Manhanvien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Ngaysinh {
            get {
                return this.NgaysinhField;
            }
            set {
                if ((this.NgaysinhField.Equals(value) != true)) {
                    this.NgaysinhField = value;
                    this.RaisePropertyChanged("Ngaysinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Phai {
            get {
                return this.PhaiField;
            }
            set {
                if ((this.PhaiField.Equals(value) != true)) {
                    this.PhaiField = value;
                    this.RaisePropertyChanged("Phai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tennhanvien {
            get {
                return this.TennhanvienField;
            }
            set {
                if ((object.ReferenceEquals(this.TennhanvienField, value) != true)) {
                    this.TennhanvienField = value;
                    this.RaisePropertyChanged("Tennhanvien");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceNhanVien.IServiceNhanVien")]
    public interface IServiceNhanVien {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNhanVien/CountListNV", ReplyAction="http://tempuri.org/IServiceNhanVien/CountListNVResponse")]
        int CountListNV();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNhanVien/CountListNV", ReplyAction="http://tempuri.org/IServiceNhanVien/CountListNVResponse")]
        System.Threading.Tasks.Task<int> CountListNVAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNhanVien/CountChucvuQL", ReplyAction="http://tempuri.org/IServiceNhanVien/CountChucvuQLResponse")]
        int CountChucvuQL();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNhanVien/CountChucvuQL", ReplyAction="http://tempuri.org/IServiceNhanVien/CountChucvuQLResponse")]
        System.Threading.Tasks.Task<int> CountChucvuQLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNhanVien/CountChucvuNV", ReplyAction="http://tempuri.org/IServiceNhanVien/CountChucvuNVResponse")]
        int CountChucvuNV();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNhanVien/CountChucvuNV", ReplyAction="http://tempuri.org/IServiceNhanVien/CountChucvuNVResponse")]
        System.Threading.Tasks.Task<int> CountChucvuNVAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNhanVien/getListNhanVienAll", ReplyAction="http://tempuri.org/IServiceNhanVien/getListNhanVienAllResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO[] getListNhanVienAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNhanVien/getListNhanVienAll", ReplyAction="http://tempuri.org/IServiceNhanVien/getListNhanVienAllResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO[]> getListNhanVienAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNhanVien/getListNhanVienLMAll", ReplyAction="http://tempuri.org/IServiceNhanVien/getListNhanVienLMAllResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO[] getListNhanVienLMAll(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNhanVien/getListNhanVienLMAll", ReplyAction="http://tempuri.org/IServiceNhanVien/getListNhanVienLMAllResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO[]> getListNhanVienLMAllAsync(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNhanVien/getNhanVienByID", ReplyAction="http://tempuri.org/IServiceNhanVien/getNhanVienByIDResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO getNhanVienByID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNhanVien/getNhanVienByID", ReplyAction="http://tempuri.org/IServiceNhanVien/getNhanVienByIDResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO> getNhanVienByIDAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNhanVien/getListNhanVienByName", ReplyAction="http://tempuri.org/IServiceNhanVien/getListNhanVienByNameResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO[] getListNhanVienByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNhanVien/getListNhanVienByName", ReplyAction="http://tempuri.org/IServiceNhanVien/getListNhanVienByNameResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO[]> getListNhanVienByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNhanVien/getListNhanVienByChucvu", ReplyAction="http://tempuri.org/IServiceNhanVien/getListNhanVienByChucvuResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO[] getListNhanVienByChucvu(string chucvu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNhanVien/getListNhanVienByChucvu", ReplyAction="http://tempuri.org/IServiceNhanVien/getListNhanVienByChucvuResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO[]> getListNhanVienByChucvuAsync(string chucvu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNhanVien/getLikeNhanVienByID", ReplyAction="http://tempuri.org/IServiceNhanVien/getLikeNhanVienByIDResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO[] getLikeNhanVienByID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNhanVien/getLikeNhanVienByID", ReplyAction="http://tempuri.org/IServiceNhanVien/getLikeNhanVienByIDResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO[]> getLikeNhanVienByIDAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNhanVien/getListLikeNhanVienByName", ReplyAction="http://tempuri.org/IServiceNhanVien/getListLikeNhanVienByNameResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO[] getListLikeNhanVienByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNhanVien/getListLikeNhanVienByName", ReplyAction="http://tempuri.org/IServiceNhanVien/getListLikeNhanVienByNameResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO[]> getListLikeNhanVienByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNhanVien/insertNhanVien", ReplyAction="http://tempuri.org/IServiceNhanVien/insertNhanVienResponse")]
        int insertNhanVien(WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO nvDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNhanVien/insertNhanVien", ReplyAction="http://tempuri.org/IServiceNhanVien/insertNhanVienResponse")]
        System.Threading.Tasks.Task<int> insertNhanVienAsync(WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO nvDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNhanVien/deleteNhanVien", ReplyAction="http://tempuri.org/IServiceNhanVien/deleteNhanVienResponse")]
        int deleteNhanVien(string IDNhanVien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNhanVien/deleteNhanVien", ReplyAction="http://tempuri.org/IServiceNhanVien/deleteNhanVienResponse")]
        System.Threading.Tasks.Task<int> deleteNhanVienAsync(string IDNhanVien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNhanVien/updateNhanVien", ReplyAction="http://tempuri.org/IServiceNhanVien/updateNhanVienResponse")]
        int updateNhanVien(WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO nvDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNhanVien/updateNhanVien", ReplyAction="http://tempuri.org/IServiceNhanVien/updateNhanVienResponse")]
        System.Threading.Tasks.Task<int> updateNhanVienAsync(WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO nvDTO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceNhanVienChannel : WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.IServiceNhanVien, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceNhanVienClient : System.ServiceModel.ClientBase<WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.IServiceNhanVien>, WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.IServiceNhanVien {
        
        public ServiceNhanVienClient() {
        }
        
        public ServiceNhanVienClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceNhanVienClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceNhanVienClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceNhanVienClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CountListNV() {
            return base.Channel.CountListNV();
        }
        
        public System.Threading.Tasks.Task<int> CountListNVAsync() {
            return base.Channel.CountListNVAsync();
        }
        
        public int CountChucvuQL() {
            return base.Channel.CountChucvuQL();
        }
        
        public System.Threading.Tasks.Task<int> CountChucvuQLAsync() {
            return base.Channel.CountChucvuQLAsync();
        }
        
        public int CountChucvuNV() {
            return base.Channel.CountChucvuNV();
        }
        
        public System.Threading.Tasks.Task<int> CountChucvuNVAsync() {
            return base.Channel.CountChucvuNVAsync();
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO[] getListNhanVienAll() {
            return base.Channel.getListNhanVienAll();
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO[]> getListNhanVienAllAsync() {
            return base.Channel.getListNhanVienAllAsync();
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO[] getListNhanVienLMAll(int a) {
            return base.Channel.getListNhanVienLMAll(a);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO[]> getListNhanVienLMAllAsync(int a) {
            return base.Channel.getListNhanVienLMAllAsync(a);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO getNhanVienByID(string id) {
            return base.Channel.getNhanVienByID(id);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO> getNhanVienByIDAsync(string id) {
            return base.Channel.getNhanVienByIDAsync(id);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO[] getListNhanVienByName(string name) {
            return base.Channel.getListNhanVienByName(name);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO[]> getListNhanVienByNameAsync(string name) {
            return base.Channel.getListNhanVienByNameAsync(name);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO[] getListNhanVienByChucvu(string chucvu) {
            return base.Channel.getListNhanVienByChucvu(chucvu);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO[]> getListNhanVienByChucvuAsync(string chucvu) {
            return base.Channel.getListNhanVienByChucvuAsync(chucvu);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO[] getLikeNhanVienByID(string id) {
            return base.Channel.getLikeNhanVienByID(id);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO[]> getLikeNhanVienByIDAsync(string id) {
            return base.Channel.getLikeNhanVienByIDAsync(id);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO[] getListLikeNhanVienByName(string name) {
            return base.Channel.getListLikeNhanVienByName(name);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO[]> getListLikeNhanVienByNameAsync(string name) {
            return base.Channel.getListLikeNhanVienByNameAsync(name);
        }
        
        public int insertNhanVien(WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO nvDTO) {
            return base.Channel.insertNhanVien(nvDTO);
        }
        
        public System.Threading.Tasks.Task<int> insertNhanVienAsync(WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO nvDTO) {
            return base.Channel.insertNhanVienAsync(nvDTO);
        }
        
        public int deleteNhanVien(string IDNhanVien) {
            return base.Channel.deleteNhanVien(IDNhanVien);
        }
        
        public System.Threading.Tasks.Task<int> deleteNhanVienAsync(string IDNhanVien) {
            return base.Channel.deleteNhanVienAsync(IDNhanVien);
        }
        
        public int updateNhanVien(WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO nvDTO) {
            return base.Channel.updateNhanVien(nvDTO);
        }
        
        public System.Threading.Tasks.Task<int> updateNhanVienAsync(WCF_QuanLyKhachSanForm.ServiceReferenceNhanVien.NhanVienDTO nvDTO) {
            return base.Channel.updateNhanVienAsync(nvDTO);
        }
    }
}
