//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChiTietThuePhongDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceQuanLyKhachSan")]
    [System.SerializableAttribute()]
    public partial class ChiTietThuePhongDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MadichvuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaphieuthueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaphongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoluongField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Madichvu {
            get {
                return this.MadichvuField;
            }
            set {
                if ((object.ReferenceEquals(this.MadichvuField, value) != true)) {
                    this.MadichvuField = value;
                    this.RaisePropertyChanged("Madichvu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Maphieuthue {
            get {
                return this.MaphieuthueField;
            }
            set {
                if ((object.ReferenceEquals(this.MaphieuthueField, value) != true)) {
                    this.MaphieuthueField = value;
                    this.RaisePropertyChanged("Maphieuthue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Maphong {
            get {
                return this.MaphongField;
            }
            set {
                if ((object.ReferenceEquals(this.MaphongField, value) != true)) {
                    this.MaphongField = value;
                    this.RaisePropertyChanged("Maphong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Ngay {
            get {
                return this.NgayField;
            }
            set {
                if ((this.NgayField.Equals(value) != true)) {
                    this.NgayField = value;
                    this.RaisePropertyChanged("Ngay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Soluong {
            get {
                return this.SoluongField;
            }
            set {
                if ((this.SoluongField.Equals(value) != true)) {
                    this.SoluongField = value;
                    this.RaisePropertyChanged("Soluong");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceChiTietThuePhong.IServiceChiTietThuePhong")]
    public interface IServiceChiTietThuePhong {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietThuePhong/CountListcttp", ReplyAction="http://tempuri.org/IServiceChiTietThuePhong/CountListcttpResponse")]
        int CountListcttp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietThuePhong/CountListcttp", ReplyAction="http://tempuri.org/IServiceChiTietThuePhong/CountListcttpResponse")]
        System.Threading.Tasks.Task<int> CountListcttpAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietThuePhong/getListChiTietThuePhongAll", ReplyAction="http://tempuri.org/IServiceChiTietThuePhong/getListChiTietThuePhongAllResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO[] getListChiTietThuePhongAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietThuePhong/getListChiTietThuePhongAll", ReplyAction="http://tempuri.org/IServiceChiTietThuePhong/getListChiTietThuePhongAllResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO[]> getListChiTietThuePhongAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietThuePhong/getListChiTietThuePhongLMAll", ReplyAction="http://tempuri.org/IServiceChiTietThuePhong/getListChiTietThuePhongLMAllResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO[] getListChiTietThuePhongLMAll(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietThuePhong/getListChiTietThuePhongLMAll", ReplyAction="http://tempuri.org/IServiceChiTietThuePhong/getListChiTietThuePhongLMAllResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO[]> getListChiTietThuePhongLMAllAsync(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietThuePhong/getChiTietThuePhongByID", ReplyAction="http://tempuri.org/IServiceChiTietThuePhong/getChiTietThuePhongByIDResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO[] getChiTietThuePhongByID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietThuePhong/getChiTietThuePhongByID", ReplyAction="http://tempuri.org/IServiceChiTietThuePhong/getChiTietThuePhongByIDResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO[]> getChiTietThuePhongByIDAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietThuePhong/getListChiTietThuePhongByName", ReplyAction="http://tempuri.org/IServiceChiTietThuePhong/getListChiTietThuePhongByNameResponse" +
            "")]
        WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO[] getListChiTietThuePhongByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietThuePhong/getListChiTietThuePhongByName", ReplyAction="http://tempuri.org/IServiceChiTietThuePhong/getListChiTietThuePhongByNameResponse" +
            "")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO[]> getListChiTietThuePhongByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietThuePhong/getLikeChiTietThuePhongByID", ReplyAction="http://tempuri.org/IServiceChiTietThuePhong/getLikeChiTietThuePhongByIDResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO[] getLikeChiTietThuePhongByID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietThuePhong/getLikeChiTietThuePhongByID", ReplyAction="http://tempuri.org/IServiceChiTietThuePhong/getLikeChiTietThuePhongByIDResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO[]> getLikeChiTietThuePhongByIDAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietThuePhong/getListLikeChiTietThuePhongByName", ReplyAction="http://tempuri.org/IServiceChiTietThuePhong/getListLikeChiTietThuePhongByNameResp" +
            "onse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO[] getListLikeChiTietThuePhongByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietThuePhong/getListLikeChiTietThuePhongByName", ReplyAction="http://tempuri.org/IServiceChiTietThuePhong/getListLikeChiTietThuePhongByNameResp" +
            "onse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO[]> getListLikeChiTietThuePhongByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietThuePhong/insertChiTietThuePhong", ReplyAction="http://tempuri.org/IServiceChiTietThuePhong/insertChiTietThuePhongResponse")]
        int insertChiTietThuePhong(WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO cttpDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietThuePhong/insertChiTietThuePhong", ReplyAction="http://tempuri.org/IServiceChiTietThuePhong/insertChiTietThuePhongResponse")]
        System.Threading.Tasks.Task<int> insertChiTietThuePhongAsync(WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO cttpDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietThuePhong/deleteChiTietThuePhong", ReplyAction="http://tempuri.org/IServiceChiTietThuePhong/deleteChiTietThuePhongResponse")]
        int deleteChiTietThuePhong(string IDChiTietThuePhong, string maphong, System.DateTime ngay, string madichvu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietThuePhong/deleteChiTietThuePhong", ReplyAction="http://tempuri.org/IServiceChiTietThuePhong/deleteChiTietThuePhongResponse")]
        System.Threading.Tasks.Task<int> deleteChiTietThuePhongAsync(string IDChiTietThuePhong, string maphong, System.DateTime ngay, string madichvu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietThuePhong/updateChiTietThuePhong", ReplyAction="http://tempuri.org/IServiceChiTietThuePhong/updateChiTietThuePhongResponse")]
        int updateChiTietThuePhong(WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO cttpDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietThuePhong/updateChiTietThuePhong", ReplyAction="http://tempuri.org/IServiceChiTietThuePhong/updateChiTietThuePhongResponse")]
        System.Threading.Tasks.Task<int> updateChiTietThuePhongAsync(WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO cttpDTO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChiTietThuePhongChannel : WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.IServiceChiTietThuePhong, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceChiTietThuePhongClient : System.ServiceModel.ClientBase<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.IServiceChiTietThuePhong>, WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.IServiceChiTietThuePhong {
        
        public ServiceChiTietThuePhongClient() {
        }
        
        public ServiceChiTietThuePhongClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceChiTietThuePhongClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceChiTietThuePhongClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceChiTietThuePhongClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CountListcttp() {
            return base.Channel.CountListcttp();
        }
        
        public System.Threading.Tasks.Task<int> CountListcttpAsync() {
            return base.Channel.CountListcttpAsync();
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO[] getListChiTietThuePhongAll() {
            return base.Channel.getListChiTietThuePhongAll();
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO[]> getListChiTietThuePhongAllAsync() {
            return base.Channel.getListChiTietThuePhongAllAsync();
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO[] getListChiTietThuePhongLMAll(int a) {
            return base.Channel.getListChiTietThuePhongLMAll(a);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO[]> getListChiTietThuePhongLMAllAsync(int a) {
            return base.Channel.getListChiTietThuePhongLMAllAsync(a);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO[] getChiTietThuePhongByID(string id) {
            return base.Channel.getChiTietThuePhongByID(id);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO[]> getChiTietThuePhongByIDAsync(string id) {
            return base.Channel.getChiTietThuePhongByIDAsync(id);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO[] getListChiTietThuePhongByName(string name) {
            return base.Channel.getListChiTietThuePhongByName(name);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO[]> getListChiTietThuePhongByNameAsync(string name) {
            return base.Channel.getListChiTietThuePhongByNameAsync(name);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO[] getLikeChiTietThuePhongByID(string id) {
            return base.Channel.getLikeChiTietThuePhongByID(id);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO[]> getLikeChiTietThuePhongByIDAsync(string id) {
            return base.Channel.getLikeChiTietThuePhongByIDAsync(id);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO[] getListLikeChiTietThuePhongByName(string name) {
            return base.Channel.getListLikeChiTietThuePhongByName(name);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO[]> getListLikeChiTietThuePhongByNameAsync(string name) {
            return base.Channel.getListLikeChiTietThuePhongByNameAsync(name);
        }
        
        public int insertChiTietThuePhong(WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO cttpDTO) {
            return base.Channel.insertChiTietThuePhong(cttpDTO);
        }
        
        public System.Threading.Tasks.Task<int> insertChiTietThuePhongAsync(WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO cttpDTO) {
            return base.Channel.insertChiTietThuePhongAsync(cttpDTO);
        }
        
        public int deleteChiTietThuePhong(string IDChiTietThuePhong, string maphong, System.DateTime ngay, string madichvu) {
            return base.Channel.deleteChiTietThuePhong(IDChiTietThuePhong, maphong, ngay, madichvu);
        }
        
        public System.Threading.Tasks.Task<int> deleteChiTietThuePhongAsync(string IDChiTietThuePhong, string maphong, System.DateTime ngay, string madichvu) {
            return base.Channel.deleteChiTietThuePhongAsync(IDChiTietThuePhong, maphong, ngay, madichvu);
        }
        
        public int updateChiTietThuePhong(WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO cttpDTO) {
            return base.Channel.updateChiTietThuePhong(cttpDTO);
        }
        
        public System.Threading.Tasks.Task<int> updateChiTietThuePhongAsync(WCF_QuanLyKhachSanForm.ServiceReferenceChiTietThuePhong.ChiTietThuePhongDTO cttpDTO) {
            return base.Channel.updateChiTietThuePhongAsync(cttpDTO);
        }
    }
}
