//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_QuanLyKhachSanForm.ServiceReferenceDichVu {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DichVuDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceQuanLyKhachSan")]
    [System.SerializableAttribute()]
    public partial class DichVuDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DonvitinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal GiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MadichvuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TendichvuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Donvitinh {
            get {
                return this.DonvitinhField;
            }
            set {
                if ((object.ReferenceEquals(this.DonvitinhField, value) != true)) {
                    this.DonvitinhField = value;
                    this.RaisePropertyChanged("Donvitinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Gia {
            get {
                return this.GiaField;
            }
            set {
                if ((this.GiaField.Equals(value) != true)) {
                    this.GiaField = value;
                    this.RaisePropertyChanged("Gia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Madichvu {
            get {
                return this.MadichvuField;
            }
            set {
                if ((object.ReferenceEquals(this.MadichvuField, value) != true)) {
                    this.MadichvuField = value;
                    this.RaisePropertyChanged("Madichvu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tendichvu {
            get {
                return this.TendichvuField;
            }
            set {
                if ((object.ReferenceEquals(this.TendichvuField, value) != true)) {
                    this.TendichvuField = value;
                    this.RaisePropertyChanged("Tendichvu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDichVu.IServiceDichVu")]
    public interface IServiceDichVu {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDichVu/CountListdv", ReplyAction="http://tempuri.org/IServiceDichVu/CountListdvResponse")]
        int CountListdv();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDichVu/CountListdv", ReplyAction="http://tempuri.org/IServiceDichVu/CountListdvResponse")]
        System.Threading.Tasks.Task<int> CountListdvAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDichVu/getListDichVuAll", ReplyAction="http://tempuri.org/IServiceDichVu/getListDichVuAllResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO[] getListDichVuAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDichVu/getListDichVuAll", ReplyAction="http://tempuri.org/IServiceDichVu/getListDichVuAllResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO[]> getListDichVuAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDichVu/getListDichVuLMAll", ReplyAction="http://tempuri.org/IServiceDichVu/getListDichVuLMAllResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO[] getListDichVuLMAll(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDichVu/getListDichVuLMAll", ReplyAction="http://tempuri.org/IServiceDichVu/getListDichVuLMAllResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO[]> getListDichVuLMAllAsync(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDichVu/getDichVuByID", ReplyAction="http://tempuri.org/IServiceDichVu/getDichVuByIDResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO getDichVuByID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDichVu/getDichVuByID", ReplyAction="http://tempuri.org/IServiceDichVu/getDichVuByIDResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO> getDichVuByIDAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDichVu/getListDichVuByName", ReplyAction="http://tempuri.org/IServiceDichVu/getListDichVuByNameResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO[] getListDichVuByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDichVu/getListDichVuByName", ReplyAction="http://tempuri.org/IServiceDichVu/getListDichVuByNameResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO[]> getListDichVuByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDichVu/getLikeDichVuByID", ReplyAction="http://tempuri.org/IServiceDichVu/getLikeDichVuByIDResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO[] getLikeDichVuByID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDichVu/getLikeDichVuByID", ReplyAction="http://tempuri.org/IServiceDichVu/getLikeDichVuByIDResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO[]> getLikeDichVuByIDAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDichVu/getListLikeDichVuByName", ReplyAction="http://tempuri.org/IServiceDichVu/getListLikeDichVuByNameResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO[] getListLikeDichVuByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDichVu/getListLikeDichVuByName", ReplyAction="http://tempuri.org/IServiceDichVu/getListLikeDichVuByNameResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO[]> getListLikeDichVuByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDichVu/insertDichVu", ReplyAction="http://tempuri.org/IServiceDichVu/insertDichVuResponse")]
        int insertDichVu(WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO dvDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDichVu/insertDichVu", ReplyAction="http://tempuri.org/IServiceDichVu/insertDichVuResponse")]
        System.Threading.Tasks.Task<int> insertDichVuAsync(WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO dvDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDichVu/deleteDichVu", ReplyAction="http://tempuri.org/IServiceDichVu/deleteDichVuResponse")]
        int deleteDichVu(string IDDV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDichVu/deleteDichVu", ReplyAction="http://tempuri.org/IServiceDichVu/deleteDichVuResponse")]
        System.Threading.Tasks.Task<int> deleteDichVuAsync(string IDDV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDichVu/updateDichVu", ReplyAction="http://tempuri.org/IServiceDichVu/updateDichVuResponse")]
        int updateDichVu(WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO dvDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDichVu/updateDichVu", ReplyAction="http://tempuri.org/IServiceDichVu/updateDichVuResponse")]
        System.Threading.Tasks.Task<int> updateDichVuAsync(WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO dvDTO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDichVuChannel : WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.IServiceDichVu, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDichVuClient : System.ServiceModel.ClientBase<WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.IServiceDichVu>, WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.IServiceDichVu {
        
        public ServiceDichVuClient() {
        }
        
        public ServiceDichVuClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDichVuClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDichVuClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDichVuClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CountListdv() {
            return base.Channel.CountListdv();
        }
        
        public System.Threading.Tasks.Task<int> CountListdvAsync() {
            return base.Channel.CountListdvAsync();
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO[] getListDichVuAll() {
            return base.Channel.getListDichVuAll();
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO[]> getListDichVuAllAsync() {
            return base.Channel.getListDichVuAllAsync();
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO[] getListDichVuLMAll(int a) {
            return base.Channel.getListDichVuLMAll(a);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO[]> getListDichVuLMAllAsync(int a) {
            return base.Channel.getListDichVuLMAllAsync(a);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO getDichVuByID(string id) {
            return base.Channel.getDichVuByID(id);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO> getDichVuByIDAsync(string id) {
            return base.Channel.getDichVuByIDAsync(id);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO[] getListDichVuByName(string name) {
            return base.Channel.getListDichVuByName(name);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO[]> getListDichVuByNameAsync(string name) {
            return base.Channel.getListDichVuByNameAsync(name);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO[] getLikeDichVuByID(string id) {
            return base.Channel.getLikeDichVuByID(id);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO[]> getLikeDichVuByIDAsync(string id) {
            return base.Channel.getLikeDichVuByIDAsync(id);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO[] getListLikeDichVuByName(string name) {
            return base.Channel.getListLikeDichVuByName(name);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO[]> getListLikeDichVuByNameAsync(string name) {
            return base.Channel.getListLikeDichVuByNameAsync(name);
        }
        
        public int insertDichVu(WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO dvDTO) {
            return base.Channel.insertDichVu(dvDTO);
        }
        
        public System.Threading.Tasks.Task<int> insertDichVuAsync(WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO dvDTO) {
            return base.Channel.insertDichVuAsync(dvDTO);
        }
        
        public int deleteDichVu(string IDDV) {
            return base.Channel.deleteDichVu(IDDV);
        }
        
        public System.Threading.Tasks.Task<int> deleteDichVuAsync(string IDDV) {
            return base.Channel.deleteDichVuAsync(IDDV);
        }
        
        public int updateDichVu(WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO dvDTO) {
            return base.Channel.updateDichVu(dvDTO);
        }
        
        public System.Threading.Tasks.Task<int> updateDichVuAsync(WCF_QuanLyKhachSanForm.ServiceReferenceDichVu.DichVuDTO dvDTO) {
            return base.Channel.updateDichVuAsync(dvDTO);
        }
    }
}
