//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_QuanLyKhachSanForm.ServiceReferenceLoaiPhong {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoaiPhongDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceQuanLyKhachSan")]
    [System.SerializableAttribute()]
    public partial class LoaiPhongDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal GiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaloaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SonguoiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Gia {
            get {
                return this.GiaField;
            }
            set {
                if ((this.GiaField.Equals(value) != true)) {
                    this.GiaField = value;
                    this.RaisePropertyChanged("Gia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Maloai {
            get {
                return this.MaloaiField;
            }
            set {
                if ((object.ReferenceEquals(this.MaloaiField, value) != true)) {
                    this.MaloaiField = value;
                    this.RaisePropertyChanged("Maloai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Songuoi {
            get {
                return this.SonguoiField;
            }
            set {
                if ((this.SonguoiField.Equals(value) != true)) {
                    this.SonguoiField = value;
                    this.RaisePropertyChanged("Songuoi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceLoaiPhong.IServiceLoaiPhong")]
    public interface IServiceLoaiPhong {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoaiPhong/CountListLP", ReplyAction="http://tempuri.org/IServiceLoaiPhong/CountListLPResponse")]
        int CountListLP();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoaiPhong/CountListLP", ReplyAction="http://tempuri.org/IServiceLoaiPhong/CountListLPResponse")]
        System.Threading.Tasks.Task<int> CountListLPAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoaiPhong/getListLoaiPhongAll", ReplyAction="http://tempuri.org/IServiceLoaiPhong/getListLoaiPhongAllResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceLoaiPhong.LoaiPhongDTO[] getListLoaiPhongAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoaiPhong/getListLoaiPhongAll", ReplyAction="http://tempuri.org/IServiceLoaiPhong/getListLoaiPhongAllResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceLoaiPhong.LoaiPhongDTO[]> getListLoaiPhongAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoaiPhong/getListLoaiPhongLMAll", ReplyAction="http://tempuri.org/IServiceLoaiPhong/getListLoaiPhongLMAllResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceLoaiPhong.LoaiPhongDTO[] getListLoaiPhongLMAll(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoaiPhong/getListLoaiPhongLMAll", ReplyAction="http://tempuri.org/IServiceLoaiPhong/getListLoaiPhongLMAllResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceLoaiPhong.LoaiPhongDTO[]> getListLoaiPhongLMAllAsync(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoaiPhong/getLoaiPhongByID", ReplyAction="http://tempuri.org/IServiceLoaiPhong/getLoaiPhongByIDResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceLoaiPhong.LoaiPhongDTO getLoaiPhongByID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoaiPhong/getLoaiPhongByID", ReplyAction="http://tempuri.org/IServiceLoaiPhong/getLoaiPhongByIDResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceLoaiPhong.LoaiPhongDTO> getLoaiPhongByIDAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoaiPhong/getLikeLoaiPhongByID", ReplyAction="http://tempuri.org/IServiceLoaiPhong/getLikeLoaiPhongByIDResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceLoaiPhong.LoaiPhongDTO[] getLikeLoaiPhongByID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoaiPhong/getLikeLoaiPhongByID", ReplyAction="http://tempuri.org/IServiceLoaiPhong/getLikeLoaiPhongByIDResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceLoaiPhong.LoaiPhongDTO[]> getLikeLoaiPhongByIDAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoaiPhong/insertLoaiPhong", ReplyAction="http://tempuri.org/IServiceLoaiPhong/insertLoaiPhongResponse")]
        int insertLoaiPhong(WCF_QuanLyKhachSanForm.ServiceReferenceLoaiPhong.LoaiPhongDTO lpDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoaiPhong/insertLoaiPhong", ReplyAction="http://tempuri.org/IServiceLoaiPhong/insertLoaiPhongResponse")]
        System.Threading.Tasks.Task<int> insertLoaiPhongAsync(WCF_QuanLyKhachSanForm.ServiceReferenceLoaiPhong.LoaiPhongDTO lpDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoaiPhong/deleteLoaiPhong", ReplyAction="http://tempuri.org/IServiceLoaiPhong/deleteLoaiPhongResponse")]
        int deleteLoaiPhong(string IDLoaiPhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoaiPhong/deleteLoaiPhong", ReplyAction="http://tempuri.org/IServiceLoaiPhong/deleteLoaiPhongResponse")]
        System.Threading.Tasks.Task<int> deleteLoaiPhongAsync(string IDLoaiPhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoaiPhong/updateLoaiPhong", ReplyAction="http://tempuri.org/IServiceLoaiPhong/updateLoaiPhongResponse")]
        int updateLoaiPhong(WCF_QuanLyKhachSanForm.ServiceReferenceLoaiPhong.LoaiPhongDTO lpDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoaiPhong/updateLoaiPhong", ReplyAction="http://tempuri.org/IServiceLoaiPhong/updateLoaiPhongResponse")]
        System.Threading.Tasks.Task<int> updateLoaiPhongAsync(WCF_QuanLyKhachSanForm.ServiceReferenceLoaiPhong.LoaiPhongDTO lpDTO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceLoaiPhongChannel : WCF_QuanLyKhachSanForm.ServiceReferenceLoaiPhong.IServiceLoaiPhong, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceLoaiPhongClient : System.ServiceModel.ClientBase<WCF_QuanLyKhachSanForm.ServiceReferenceLoaiPhong.IServiceLoaiPhong>, WCF_QuanLyKhachSanForm.ServiceReferenceLoaiPhong.IServiceLoaiPhong {
        
        public ServiceLoaiPhongClient() {
        }
        
        public ServiceLoaiPhongClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceLoaiPhongClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLoaiPhongClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLoaiPhongClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CountListLP() {
            return base.Channel.CountListLP();
        }
        
        public System.Threading.Tasks.Task<int> CountListLPAsync() {
            return base.Channel.CountListLPAsync();
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceLoaiPhong.LoaiPhongDTO[] getListLoaiPhongAll() {
            return base.Channel.getListLoaiPhongAll();
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceLoaiPhong.LoaiPhongDTO[]> getListLoaiPhongAllAsync() {
            return base.Channel.getListLoaiPhongAllAsync();
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceLoaiPhong.LoaiPhongDTO[] getListLoaiPhongLMAll(int a) {
            return base.Channel.getListLoaiPhongLMAll(a);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceLoaiPhong.LoaiPhongDTO[]> getListLoaiPhongLMAllAsync(int a) {
            return base.Channel.getListLoaiPhongLMAllAsync(a);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceLoaiPhong.LoaiPhongDTO getLoaiPhongByID(string id) {
            return base.Channel.getLoaiPhongByID(id);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceLoaiPhong.LoaiPhongDTO> getLoaiPhongByIDAsync(string id) {
            return base.Channel.getLoaiPhongByIDAsync(id);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceLoaiPhong.LoaiPhongDTO[] getLikeLoaiPhongByID(string id) {
            return base.Channel.getLikeLoaiPhongByID(id);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceLoaiPhong.LoaiPhongDTO[]> getLikeLoaiPhongByIDAsync(string id) {
            return base.Channel.getLikeLoaiPhongByIDAsync(id);
        }
        
        public int insertLoaiPhong(WCF_QuanLyKhachSanForm.ServiceReferenceLoaiPhong.LoaiPhongDTO lpDTO) {
            return base.Channel.insertLoaiPhong(lpDTO);
        }
        
        public System.Threading.Tasks.Task<int> insertLoaiPhongAsync(WCF_QuanLyKhachSanForm.ServiceReferenceLoaiPhong.LoaiPhongDTO lpDTO) {
            return base.Channel.insertLoaiPhongAsync(lpDTO);
        }
        
        public int deleteLoaiPhong(string IDLoaiPhong) {
            return base.Channel.deleteLoaiPhong(IDLoaiPhong);
        }
        
        public System.Threading.Tasks.Task<int> deleteLoaiPhongAsync(string IDLoaiPhong) {
            return base.Channel.deleteLoaiPhongAsync(IDLoaiPhong);
        }
        
        public int updateLoaiPhong(WCF_QuanLyKhachSanForm.ServiceReferenceLoaiPhong.LoaiPhongDTO lpDTO) {
            return base.Channel.updateLoaiPhong(lpDTO);
        }
        
        public System.Threading.Tasks.Task<int> updateLoaiPhongAsync(WCF_QuanLyKhachSanForm.ServiceReferenceLoaiPhong.LoaiPhongDTO lpDTO) {
            return base.Channel.updateLoaiPhongAsync(lpDTO);
        }
    }
}
