//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_QuanLyKhachSanForm.ServiceReferenceVatTu {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VatTuDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceQuanLyKhachSan")]
    [System.SerializableAttribute()]
    public partial class VatTuDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MavattuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenvattuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mavattu {
            get {
                return this.MavattuField;
            }
            set {
                if ((object.ReferenceEquals(this.MavattuField, value) != true)) {
                    this.MavattuField = value;
                    this.RaisePropertyChanged("Mavattu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tenvattu {
            get {
                return this.TenvattuField;
            }
            set {
                if ((object.ReferenceEquals(this.TenvattuField, value) != true)) {
                    this.TenvattuField = value;
                    this.RaisePropertyChanged("Tenvattu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceVatTu.IServiceVatTu")]
    public interface IServiceVatTu {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVatTu/CountListvVT", ReplyAction="http://tempuri.org/IServiceVatTu/CountListvVTResponse")]
        int CountListvVT();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVatTu/CountListvVT", ReplyAction="http://tempuri.org/IServiceVatTu/CountListvVTResponse")]
        System.Threading.Tasks.Task<int> CountListvVTAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVatTu/getListVatTuAll", ReplyAction="http://tempuri.org/IServiceVatTu/getListVatTuAllResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO[] getListVatTuAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVatTu/getListVatTuAll", ReplyAction="http://tempuri.org/IServiceVatTu/getListVatTuAllResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO[]> getListVatTuAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVatTu/getListVatTuLMAll", ReplyAction="http://tempuri.org/IServiceVatTu/getListVatTuLMAllResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO[] getListVatTuLMAll(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVatTu/getListVatTuLMAll", ReplyAction="http://tempuri.org/IServiceVatTu/getListVatTuLMAllResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO[]> getListVatTuLMAllAsync(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVatTu/getVatTuByID", ReplyAction="http://tempuri.org/IServiceVatTu/getVatTuByIDResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO getVatTuByID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVatTu/getVatTuByID", ReplyAction="http://tempuri.org/IServiceVatTu/getVatTuByIDResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO> getVatTuByIDAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVatTu/getListVatTuByName", ReplyAction="http://tempuri.org/IServiceVatTu/getListVatTuByNameResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO[] getListVatTuByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVatTu/getListVatTuByName", ReplyAction="http://tempuri.org/IServiceVatTu/getListVatTuByNameResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO[]> getListVatTuByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVatTu/getLikeVatTuByID", ReplyAction="http://tempuri.org/IServiceVatTu/getLikeVatTuByIDResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO[] getLikeVatTuByID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVatTu/getLikeVatTuByID", ReplyAction="http://tempuri.org/IServiceVatTu/getLikeVatTuByIDResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO[]> getLikeVatTuByIDAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVatTu/getListLikeVatTuByName", ReplyAction="http://tempuri.org/IServiceVatTu/getListLikeVatTuByNameResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO[] getListLikeVatTuByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVatTu/getListLikeVatTuByName", ReplyAction="http://tempuri.org/IServiceVatTu/getListLikeVatTuByNameResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO[]> getListLikeVatTuByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVatTu/insertVatTu", ReplyAction="http://tempuri.org/IServiceVatTu/insertVatTuResponse")]
        int insertVatTu(WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO vtDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVatTu/insertVatTu", ReplyAction="http://tempuri.org/IServiceVatTu/insertVatTuResponse")]
        System.Threading.Tasks.Task<int> insertVatTuAsync(WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO vtDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVatTu/deleteVatTu", ReplyAction="http://tempuri.org/IServiceVatTu/deleteVatTuResponse")]
        int deleteVatTu(string IDVatTu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVatTu/deleteVatTu", ReplyAction="http://tempuri.org/IServiceVatTu/deleteVatTuResponse")]
        System.Threading.Tasks.Task<int> deleteVatTuAsync(string IDVatTu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVatTu/updateVatTu", ReplyAction="http://tempuri.org/IServiceVatTu/updateVatTuResponse")]
        int updateVatTu(WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO vtDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVatTu/updateVatTu", ReplyAction="http://tempuri.org/IServiceVatTu/updateVatTuResponse")]
        System.Threading.Tasks.Task<int> updateVatTuAsync(WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO vtDTO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceVatTuChannel : WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.IServiceVatTu, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceVatTuClient : System.ServiceModel.ClientBase<WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.IServiceVatTu>, WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.IServiceVatTu {
        
        public ServiceVatTuClient() {
        }
        
        public ServiceVatTuClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceVatTuClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceVatTuClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceVatTuClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CountListvVT() {
            return base.Channel.CountListvVT();
        }
        
        public System.Threading.Tasks.Task<int> CountListvVTAsync() {
            return base.Channel.CountListvVTAsync();
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO[] getListVatTuAll() {
            return base.Channel.getListVatTuAll();
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO[]> getListVatTuAllAsync() {
            return base.Channel.getListVatTuAllAsync();
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO[] getListVatTuLMAll(int a) {
            return base.Channel.getListVatTuLMAll(a);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO[]> getListVatTuLMAllAsync(int a) {
            return base.Channel.getListVatTuLMAllAsync(a);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO getVatTuByID(string id) {
            return base.Channel.getVatTuByID(id);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO> getVatTuByIDAsync(string id) {
            return base.Channel.getVatTuByIDAsync(id);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO[] getListVatTuByName(string name) {
            return base.Channel.getListVatTuByName(name);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO[]> getListVatTuByNameAsync(string name) {
            return base.Channel.getListVatTuByNameAsync(name);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO[] getLikeVatTuByID(string id) {
            return base.Channel.getLikeVatTuByID(id);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO[]> getLikeVatTuByIDAsync(string id) {
            return base.Channel.getLikeVatTuByIDAsync(id);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO[] getListLikeVatTuByName(string name) {
            return base.Channel.getListLikeVatTuByName(name);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO[]> getListLikeVatTuByNameAsync(string name) {
            return base.Channel.getListLikeVatTuByNameAsync(name);
        }
        
        public int insertVatTu(WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO vtDTO) {
            return base.Channel.insertVatTu(vtDTO);
        }
        
        public System.Threading.Tasks.Task<int> insertVatTuAsync(WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO vtDTO) {
            return base.Channel.insertVatTuAsync(vtDTO);
        }
        
        public int deleteVatTu(string IDVatTu) {
            return base.Channel.deleteVatTu(IDVatTu);
        }
        
        public System.Threading.Tasks.Task<int> deleteVatTuAsync(string IDVatTu) {
            return base.Channel.deleteVatTuAsync(IDVatTu);
        }
        
        public int updateVatTu(WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO vtDTO) {
            return base.Channel.updateVatTu(vtDTO);
        }
        
        public System.Threading.Tasks.Task<int> updateVatTuAsync(WCF_QuanLyKhachSanForm.ServiceReferenceVatTu.VatTuDTO vtDTO) {
            return base.Channel.updateVatTuAsync(vtDTO);
        }
    }
}
