//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChiTietVatTuDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceQuanLyKhachSan")]
    [System.SerializableAttribute()]
    public partial class ChiTietVatTuDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaloaiphongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MavattuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoluongField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Maloaiphong {
            get {
                return this.MaloaiphongField;
            }
            set {
                if ((object.ReferenceEquals(this.MaloaiphongField, value) != true)) {
                    this.MaloaiphongField = value;
                    this.RaisePropertyChanged("Maloaiphong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mavattu {
            get {
                return this.MavattuField;
            }
            set {
                if ((object.ReferenceEquals(this.MavattuField, value) != true)) {
                    this.MavattuField = value;
                    this.RaisePropertyChanged("Mavattu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Soluong {
            get {
                return this.SoluongField;
            }
            set {
                if ((this.SoluongField.Equals(value) != true)) {
                    this.SoluongField = value;
                    this.RaisePropertyChanged("Soluong");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceChiTietVatTu.IServiceChiTietVatTu")]
    public interface IServiceChiTietVatTu {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietVatTu/CountListctvt", ReplyAction="http://tempuri.org/IServiceChiTietVatTu/CountListctvtResponse")]
        int CountListctvt();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietVatTu/CountListctvt", ReplyAction="http://tempuri.org/IServiceChiTietVatTu/CountListctvtResponse")]
        System.Threading.Tasks.Task<int> CountListctvtAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietVatTu/getListChiTietVatTuAll", ReplyAction="http://tempuri.org/IServiceChiTietVatTu/getListChiTietVatTuAllResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO[] getListChiTietVatTuAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietVatTu/getListChiTietVatTuAll", ReplyAction="http://tempuri.org/IServiceChiTietVatTu/getListChiTietVatTuAllResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO[]> getListChiTietVatTuAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietVatTu/getListChiTietVatTuLMAll", ReplyAction="http://tempuri.org/IServiceChiTietVatTu/getListChiTietVatTuLMAllResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO[] getListChiTietVatTuLMAll(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietVatTu/getListChiTietVatTuLMAll", ReplyAction="http://tempuri.org/IServiceChiTietVatTu/getListChiTietVatTuLMAllResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO[]> getListChiTietVatTuLMAllAsync(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietVatTu/getChiTietVatTuByID", ReplyAction="http://tempuri.org/IServiceChiTietVatTu/getChiTietVatTuByIDResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO getChiTietVatTuByID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietVatTu/getChiTietVatTuByID", ReplyAction="http://tempuri.org/IServiceChiTietVatTu/getChiTietVatTuByIDResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO> getChiTietVatTuByIDAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietVatTu/getListChiTietVatTuByMaLP", ReplyAction="http://tempuri.org/IServiceChiTietVatTu/getListChiTietVatTuByMaLPResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO[] getListChiTietVatTuByMaLP(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietVatTu/getListChiTietVatTuByMaLP", ReplyAction="http://tempuri.org/IServiceChiTietVatTu/getListChiTietVatTuByMaLPResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO[]> getListChiTietVatTuByMaLPAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietVatTu/getLikeChiTietVatTuByID", ReplyAction="http://tempuri.org/IServiceChiTietVatTu/getLikeChiTietVatTuByIDResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO[] getLikeChiTietVatTuByID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietVatTu/getLikeChiTietVatTuByID", ReplyAction="http://tempuri.org/IServiceChiTietVatTu/getLikeChiTietVatTuByIDResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO[]> getLikeChiTietVatTuByIDAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietVatTu/getListLikeChiTietVatTuByMaLP", ReplyAction="http://tempuri.org/IServiceChiTietVatTu/getListLikeChiTietVatTuByMaLPResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO[] getListLikeChiTietVatTuByMaLP(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietVatTu/getListLikeChiTietVatTuByMaLP", ReplyAction="http://tempuri.org/IServiceChiTietVatTu/getListLikeChiTietVatTuByMaLPResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO[]> getListLikeChiTietVatTuByMaLPAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietVatTu/insertChiTietVatTu", ReplyAction="http://tempuri.org/IServiceChiTietVatTu/insertChiTietVatTuResponse")]
        int insertChiTietVatTu(WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO ctvtDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietVatTu/insertChiTietVatTu", ReplyAction="http://tempuri.org/IServiceChiTietVatTu/insertChiTietVatTuResponse")]
        System.Threading.Tasks.Task<int> insertChiTietVatTuAsync(WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO ctvtDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietVatTu/deleteChiTietVatTu", ReplyAction="http://tempuri.org/IServiceChiTietVatTu/deleteChiTietVatTuResponse")]
        int deleteChiTietVatTu(string IDNhactvtien, string idPhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietVatTu/deleteChiTietVatTu", ReplyAction="http://tempuri.org/IServiceChiTietVatTu/deleteChiTietVatTuResponse")]
        System.Threading.Tasks.Task<int> deleteChiTietVatTuAsync(string IDNhactvtien, string idPhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietVatTu/updateChiTietVatTu", ReplyAction="http://tempuri.org/IServiceChiTietVatTu/updateChiTietVatTuResponse")]
        int updateChiTietVatTu(WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO ctvtDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceChiTietVatTu/updateChiTietVatTu", ReplyAction="http://tempuri.org/IServiceChiTietVatTu/updateChiTietVatTuResponse")]
        System.Threading.Tasks.Task<int> updateChiTietVatTuAsync(WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO ctvtDTO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChiTietVatTuChannel : WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.IServiceChiTietVatTu, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceChiTietVatTuClient : System.ServiceModel.ClientBase<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.IServiceChiTietVatTu>, WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.IServiceChiTietVatTu {
        
        public ServiceChiTietVatTuClient() {
        }
        
        public ServiceChiTietVatTuClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceChiTietVatTuClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceChiTietVatTuClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceChiTietVatTuClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CountListctvt() {
            return base.Channel.CountListctvt();
        }
        
        public System.Threading.Tasks.Task<int> CountListctvtAsync() {
            return base.Channel.CountListctvtAsync();
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO[] getListChiTietVatTuAll() {
            return base.Channel.getListChiTietVatTuAll();
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO[]> getListChiTietVatTuAllAsync() {
            return base.Channel.getListChiTietVatTuAllAsync();
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO[] getListChiTietVatTuLMAll(int a) {
            return base.Channel.getListChiTietVatTuLMAll(a);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO[]> getListChiTietVatTuLMAllAsync(int a) {
            return base.Channel.getListChiTietVatTuLMAllAsync(a);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO getChiTietVatTuByID(string id) {
            return base.Channel.getChiTietVatTuByID(id);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO> getChiTietVatTuByIDAsync(string id) {
            return base.Channel.getChiTietVatTuByIDAsync(id);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO[] getListChiTietVatTuByMaLP(string name) {
            return base.Channel.getListChiTietVatTuByMaLP(name);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO[]> getListChiTietVatTuByMaLPAsync(string name) {
            return base.Channel.getListChiTietVatTuByMaLPAsync(name);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO[] getLikeChiTietVatTuByID(string id) {
            return base.Channel.getLikeChiTietVatTuByID(id);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO[]> getLikeChiTietVatTuByIDAsync(string id) {
            return base.Channel.getLikeChiTietVatTuByIDAsync(id);
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO[] getListLikeChiTietVatTuByMaLP(string name) {
            return base.Channel.getListLikeChiTietVatTuByMaLP(name);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO[]> getListLikeChiTietVatTuByMaLPAsync(string name) {
            return base.Channel.getListLikeChiTietVatTuByMaLPAsync(name);
        }
        
        public int insertChiTietVatTu(WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO ctvtDTO) {
            return base.Channel.insertChiTietVatTu(ctvtDTO);
        }
        
        public System.Threading.Tasks.Task<int> insertChiTietVatTuAsync(WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO ctvtDTO) {
            return base.Channel.insertChiTietVatTuAsync(ctvtDTO);
        }
        
        public int deleteChiTietVatTu(string IDNhactvtien, string idPhong) {
            return base.Channel.deleteChiTietVatTu(IDNhactvtien, idPhong);
        }
        
        public System.Threading.Tasks.Task<int> deleteChiTietVatTuAsync(string IDNhactvtien, string idPhong) {
            return base.Channel.deleteChiTietVatTuAsync(IDNhactvtien, idPhong);
        }
        
        public int updateChiTietVatTu(WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO ctvtDTO) {
            return base.Channel.updateChiTietVatTu(ctvtDTO);
        }
        
        public System.Threading.Tasks.Task<int> updateChiTietVatTuAsync(WCF_QuanLyKhachSanForm.ServiceReferenceChiTietVatTu.ChiTietVatTuDTO ctvtDTO) {
            return base.Channel.updateChiTietVatTuAsync(ctvtDTO);
        }
    }
}
