//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_QuanLyKhachSanForm.ServiceReferenceInHoaDonDichVu {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InHoaDonDichVuDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceQuanLyKhachSan")]
    [System.SerializableAttribute()]
    public partial class InHoaDonDichVuDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DonvitinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal GiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaPhongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MahoadonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaphieuthueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoluongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TendichvuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Donvitinh {
            get {
                return this.DonvitinhField;
            }
            set {
                if ((object.ReferenceEquals(this.DonvitinhField, value) != true)) {
                    this.DonvitinhField = value;
                    this.RaisePropertyChanged("Donvitinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Gia {
            get {
                return this.GiaField;
            }
            set {
                if ((this.GiaField.Equals(value) != true)) {
                    this.GiaField = value;
                    this.RaisePropertyChanged("Gia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaPhong {
            get {
                return this.MaPhongField;
            }
            set {
                if ((object.ReferenceEquals(this.MaPhongField, value) != true)) {
                    this.MaPhongField = value;
                    this.RaisePropertyChanged("MaPhong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mahoadon {
            get {
                return this.MahoadonField;
            }
            set {
                if ((object.ReferenceEquals(this.MahoadonField, value) != true)) {
                    this.MahoadonField = value;
                    this.RaisePropertyChanged("Mahoadon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Maphieuthue {
            get {
                return this.MaphieuthueField;
            }
            set {
                if ((object.ReferenceEquals(this.MaphieuthueField, value) != true)) {
                    this.MaphieuthueField = value;
                    this.RaisePropertyChanged("Maphieuthue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Ngay {
            get {
                return this.NgayField;
            }
            set {
                if ((this.NgayField.Equals(value) != true)) {
                    this.NgayField = value;
                    this.RaisePropertyChanged("Ngay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Soluong {
            get {
                return this.SoluongField;
            }
            set {
                if ((this.SoluongField.Equals(value) != true)) {
                    this.SoluongField = value;
                    this.RaisePropertyChanged("Soluong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tendichvu {
            get {
                return this.TendichvuField;
            }
            set {
                if ((object.ReferenceEquals(this.TendichvuField, value) != true)) {
                    this.TendichvuField = value;
                    this.RaisePropertyChanged("Tendichvu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceInHoaDonDichVu.IServiceInHoaDonDichVu")]
    public interface IServiceInHoaDonDichVu {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceInHoaDonDichVu/inhoadondv", ReplyAction="http://tempuri.org/IServiceInHoaDonDichVu/inhoadondvResponse")]
        WCF_QuanLyKhachSanForm.ServiceReferenceInHoaDonDichVu.InHoaDonDichVuDTO[] inhoadondv(string mahoadon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceInHoaDonDichVu/inhoadondv", ReplyAction="http://tempuri.org/IServiceInHoaDonDichVu/inhoadondvResponse")]
        System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceInHoaDonDichVu.InHoaDonDichVuDTO[]> inhoadondvAsync(string mahoadon);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceInHoaDonDichVuChannel : WCF_QuanLyKhachSanForm.ServiceReferenceInHoaDonDichVu.IServiceInHoaDonDichVu, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceInHoaDonDichVuClient : System.ServiceModel.ClientBase<WCF_QuanLyKhachSanForm.ServiceReferenceInHoaDonDichVu.IServiceInHoaDonDichVu>, WCF_QuanLyKhachSanForm.ServiceReferenceInHoaDonDichVu.IServiceInHoaDonDichVu {
        
        public ServiceInHoaDonDichVuClient() {
        }
        
        public ServiceInHoaDonDichVuClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceInHoaDonDichVuClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceInHoaDonDichVuClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceInHoaDonDichVuClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCF_QuanLyKhachSanForm.ServiceReferenceInHoaDonDichVu.InHoaDonDichVuDTO[] inhoadondv(string mahoadon) {
            return base.Channel.inhoadondv(mahoadon);
        }
        
        public System.Threading.Tasks.Task<WCF_QuanLyKhachSanForm.ServiceReferenceInHoaDonDichVu.InHoaDonDichVuDTO[]> inhoadondvAsync(string mahoadon) {
            return base.Channel.inhoadondvAsync(mahoadon);
        }
    }
}
